FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir prowler

COPY app ./app

CMD ["celery", "-A", "app.tasks.audit_tasks.celery_app", "worker", "--loglevel=info", "-Q", "prowler"]
